Feature/update filter api
ONSdigital/dp-dataset-exporter pull request #2
Opened 2017-08-10 15:49 UTC by CarlHembrough

### What

Once a dataset has been filtered and uploaded to S3, post a message to the filter API with the file URL, file size, and updated status.

I have also made a few fixes as part of integration testing. 
 - The neo4j query needed some tweaks
 - exported CSV rows needed newlines between them

### How to review

Describe the steps required to test the changes.

### Who can review

Anyone

2017-08-11 14:21 UTC, Matt-Guest commented on filter/store.go
> +				Size: strconv.FormatInt(size, 10),
Why do you need to do `strconv.FormatInt(size, 10)`?

2017-08-14 08:34 UTC, CarlHembrough commented on filter/store.go
> +				Size: strconv.FormatInt(size, 10),
The size field is an int64. The typical 'strconv.itoa' function takes only the int type, not int64

2017-08-15 16:59 UTC, eldeal commented on filter/store.go
> +	putBody := &observation.Filter{
Not sure the observation package is correctly named? A filter contains many observations not the other way around? O.o Haven't looked into what all the observation package is doing to know a better name though

2017-08-16 08:32 UTC, CarlHembrough commented on filter/store.go
> +	putBody := &observation.Filter{
My take on it was that its an observation filter, i.e. a filter applied to observations. I am happy to rename though if it does not make sense.

2017-08-17 13:03 UTC, nshumoogum requested changes

2017-08-17 13:03 UTC, nshumoogum commented on filter/store.go
Request to filter API will need to send an `internal_token` header equal to the secret key, defaulted to `FD0108EA-825D-411C-9B1D-41EF7727F465`. Other than that the request url and body look fine to me.

2017-08-17 13:04 UTC, nshumoogum commented on filter/store.go
The secret key should be a configurable variable.... 👍

2017-08-17 16:17 UTC, CarlHembrough commented on filter/store.go
done 👍

2017-08-18 13:20 UTC, nshumoogum requested changes

2017-08-18 13:20 UTC, nshumoogum commented on filter/store.go
> +	request.Header.Set("Internal-token", store.filterAPIAuthToken)
The filter API uses snake case `internal_token` for the header name instead of `Internal-token`.

2017-08-21 15:46 UTC, CarlHembrough commented on filter/store.go
> +	request.Header.Set("Internal-token", store.filterAPIAuthToken)
Good catch. We will have to iron out this inconsistency across the services.

2017-08-22 11:09 UTC, nshumoogum approved these changes

2017-08-24 11:09 UTC, merged