Determine state of instance/version to decide public/private
ONSdigital/dp-dataset-exporter pull request #24
Opened 2018-03-16 09:08 UTC by mattrout92

### What

- Determine the state of the instance/version to decide whether the storer should put in private/public bucket 

### How to review

- Run unit tests

### Who can review

Anyone

2018-03-19 10:32 UTC, gedge commented
`govendor update github.com/kelseyhightower/envconfig`
also there are some external `govendor list +outside` dependencies

2018-03-19 11:14 UTC, gedge requested changes
see comment

2018-03-19 11:23 UTC, gedge approved these changes

2018-04-10 12:15 UTC, nshumoogum submitted a review, later dismissed

2018-04-10 12:15 UTC, nshumoogum commented on README.md
> +<<<<<<< HEAD
Merge conflict not resolved here

2018-04-12 09:11 UTC, merged