Add CSVW generation as part of full file generation
ONSdigital/dp-dataset-exporter pull request #49
Opened 2018-07-19 11:09 UTC by eldeal

### What
Add CSVW generation as part of full file generation
-Includes new reader to allow peeking at first line of csv
-Updates dataset API client

### How to review

Make sure csvs are still generated for full outputs and filters
Make sure CSVW files are also generated on full outputs

### Who can review

Anyone

2018-07-19 11:22 UTC, eldeal reviewed
@nshumoogum ive tried to port over your existing comments so you can see that ive addressed them - if you want to take a second look?

2018-07-19 11:22 UTC, eldeal commented on csvw/csvw.go
> +			log.Info("added observation metadata column to CSVW", log.Data{"column": c})
"this is not necessarily data marking, it could be confidence interval or another stat?" - addressed

2018-07-19 11:22 UTC, eldeal commented on csvw/csvw.go
> +	//add dimension columns
"add dimension columns?" (there was a typo) - addressed

2018-07-19 11:22 UTC, eldeal commented on csvw/csvw.go
> +		log.Info("added pair of dimension columns to CSVW", log.Data{"code_column": c, "label_column": l})
"nshumoogum 2 days ago  Member
This log line would have added the one dimension column, so should it not be:

log.Info("added dimension column to CSVW", log.Data{"code_column": c, "label_column": l})

  @eldeal
eldeal 23 minutes ago  Member
No because its adding two, I could change it to 'added pair of dimension columns to CSVW' if that's clearer?"

- have tried to make more descriptive - let me know if not helpful

2018-07-19 11:22 UTC, eldeal commented on csvw/csvw.go
> +				//Target: url + "#col=need-to-store",
created story for this todo

2018-07-19 11:22 UTC, eldeal commented on csvw/csvw_test.go
> +				for _, a := range *n.Alerts {
used counter instead of index

2018-07-19 11:22 UTC, eldeal commented on csvw/csvw_test.go
> +		m := &dataset.Metadata{
Ran go vet throughout

2018-07-19 11:22 UTC, eldeal commented on reader/reader_test.go
> +	data := []byte(`Header line` + "\n" + `First line` + "\n" + `Second line` + "\n")
flattened this data out to single lines

2018-07-19 13:47 UTC, nshumoogum commented on csvw/csvw.go
> +		log.Info("added pair of dimension columns to CSVW", log.Data{"code_column": c, "label_column": l})
Yeah sorry i thought it was adding just the one. Looks good 👍

2018-07-19 13:52 UTC, nshumoogum commented on reader/reader_test.go
> +	data := []byte(`Header line` + "\n" + `First line` + "\n" + `Second line` + "\n")
So if you had used double quotes round the whole string, you wouldn't need to concatenate parts:

`"Header line\nFirst line\nSecond line\n"`

2018-07-19 13:55 UTC, nshumoogum requested changes
Just the one thing, comment above

2018-07-24 15:46 UTC, eldeal commented on reader/reader_test.go
> +	data := []byte(`Header line` + "\n" + `First line` + "\n" + `Second line` + "\n")
You can't pass a string into a byte array to my knowledge

2018-07-24 16:07 UTC, nshumoogum approved these changes

2018-07-26 11:02 UTC, merged