Release/1.11.0
ONSdigital/dp-dataset-exporter pull request #85
Opened 2020-03-23 11:43 UTC by DavidSubiros

### What

- use go modules, with go docker image 1.13.8
- healthchecker with checks
- migrated code:
  - dp-s3
  - dp-kafka
  - dp-api-clients-go

### How to review

- Unit tests should pass
- Develop env should work

### Who can review

PO Sign off.

2020-03-24 09:36 UTC, nshumoogum commented on config/config.go
> +		HealthCheckRecoveryInterval: 1 * time.Minute,
This should be `HealthcheckCriticalTimeout`

2020-03-24 09:38 UTC, nshumoogum requested changes
I would create a separate pr and update config against develop and then merge through to this release. Once this has been done and we have po sign off Im happy for this to be merged

2020-03-24 10:31 UTC, DavidSubiros commented
> I would create a separate pr and update config against develop and then merge through to this release. Once this has been done and we have po sign off Im happy for this to be merged

I just pushed the changes to this PR, I will create a feature branch, with PR against develop

2020-03-30 16:06 UTC, nshumoogum submitted a review, later dismissed

2020-04-17 09:11 UTC, nshumoogum approved these changes

2020-04-17 09:17 UTC, merged